/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLucraDSLScopeProvider extends DelegatingScopeProvider {
}
