/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LucraDSLStandaloneSetup extends LucraDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new LucraDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
