/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LucraDSLRuntimeModule extends AbstractLucraDSLRuntimeModule {
}
