/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LucraDSLUiModule extends AbstractLucraDSLUiModule {

	public LucraDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
