/**
 * generated by Xtext 2.41.0
 */
package br.com.lucra.lucraDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.lucra.lucraDSL.ComplexTypeRef#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see br.com.lucra.lucraDSL.LucraDSLPackage#getComplexTypeRef()
 * @model
 * @generated
 */
public interface ComplexTypeRef extends Type
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Element)
   * @see br.com.lucra.lucraDSL.LucraDSLPackage#getComplexTypeRef_Type()
   * @model
   * @generated
   */
  Element getType();

  /**
   * Sets the value of the '{@link br.com.lucra.lucraDSL.ComplexTypeRef#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Element value);

} // ComplexTypeRef
