/**
 * generated by Xtext 2.41.0
 */
package br.com.lucra.lucraDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.lucra.lucraDSL.EntityField#getName <em>Name</em>}</li>
 *   <li>{@link br.com.lucra.lucraDSL.EntityField#getType <em>Type</em>}</li>
 *   <li>{@link br.com.lucra.lucraDSL.EntityField#isList <em>List</em>}</li>
 *   <li>{@link br.com.lucra.lucraDSL.EntityField#isNullable <em>Nullable</em>}</li>
 *   <li>{@link br.com.lucra.lucraDSL.EntityField#getRelation <em>Relation</em>}</li>
 * </ul>
 *
 * @see br.com.lucra.lucraDSL.LucraDSLPackage#getEntityField()
 * @model
 * @generated
 */
public interface EntityField extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.com.lucra.lucraDSL.LucraDSLPackage#getEntityField_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.com.lucra.lucraDSL.EntityField#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(Type)
   * @see br.com.lucra.lucraDSL.LucraDSLPackage#getEntityField_Type()
   * @model containment="true"
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link br.com.lucra.lucraDSL.EntityField#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' attribute.
   * @see #setList(boolean)
   * @see br.com.lucra.lucraDSL.LucraDSLPackage#getEntityField_List()
   * @model
   * @generated
   */
  boolean isList();

  /**
   * Sets the value of the '{@link br.com.lucra.lucraDSL.EntityField#isList <em>List</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' attribute.
   * @see #isList()
   * @generated
   */
  void setList(boolean value);

  /**
   * Returns the value of the '<em><b>Nullable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nullable</em>' attribute.
   * @see #setNullable(boolean)
   * @see br.com.lucra.lucraDSL.LucraDSLPackage#getEntityField_Nullable()
   * @model
   * @generated
   */
  boolean isNullable();

  /**
   * Sets the value of the '{@link br.com.lucra.lucraDSL.EntityField#isNullable <em>Nullable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nullable</em>' attribute.
   * @see #isNullable()
   * @generated
   */
  void setNullable(boolean value);

  /**
   * Returns the value of the '<em><b>Relation</b></em>' attribute.
   * The literals are from the enumeration {@link br.com.lucra.lucraDSL.RelationType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relation</em>' attribute.
   * @see br.com.lucra.lucraDSL.RelationType
   * @see #setRelation(RelationType)
   * @see br.com.lucra.lucraDSL.LucraDSLPackage#getEntityField_Relation()
   * @model
   * @generated
   */
  RelationType getRelation();

  /**
   * Sets the value of the '{@link br.com.lucra.lucraDSL.EntityField#getRelation <em>Relation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relation</em>' attribute.
   * @see br.com.lucra.lucraDSL.RelationType
   * @see #getRelation()
   * @generated
   */
  void setRelation(RelationType value);

} // EntityField
