/**
 * generated by Xtext 2.41.0
 */
package br.com.lucra.lucraDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Dsl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.lucra.lucraDSL.EnumDsl#getLiterals <em>Literals</em>}</li>
 * </ul>
 *
 * @see br.com.lucra.lucraDSL.LucraDSLPackage#getEnumDsl()
 * @model
 * @generated
 */
public interface EnumDsl extends Element
{
  /**
   * Returns the value of the '<em><b>Literals</b></em>' containment reference list.
   * The list contents are of type {@link br.com.lucra.lucraDSL.EnumLiteral}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literals</em>' containment reference list.
   * @see br.com.lucra.lucraDSL.LucraDSLPackage#getEnumDsl_Literals()
   * @model containment="true"
   * @generated
   */
  EList<EnumLiteral> getLiterals();

} // EnumDsl
