/**
 * generated by Xtext 2.41.0
 */
package br.com.lucra.lucraDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lucra DSL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.lucra.lucraDSL.LucraDSL#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see br.com.lucra.lucraDSL.LucraDSLPackage#getLucraDSL()
 * @model
 * @generated
 */
public interface LucraDSL extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link br.com.lucra.lucraDSL.Element}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see br.com.lucra.lucraDSL.LucraDSLPackage#getLucraDSL_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Element> getElements();

} // LucraDSL
