/**
 * generated by Xtext 2.41.0
 */
package br.com.lucra.lucraDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.com.lucra.lucraDSL.LucraDSLFactory
 * @model kind="package"
 * @generated
 */
public interface LucraDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "lucraDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.com.br/lucra/LucraDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "lucraDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LucraDSLPackage eINSTANCE = br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.impl.LucraDSLImpl <em>Lucra DSL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.impl.LucraDSLImpl
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getLucraDSL()
   * @generated
   */
  int LUCRA_DSL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUCRA_DSL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Lucra DSL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LUCRA_DSL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.impl.TypeImpl
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.impl.PrimitiveTypeImpl
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getPrimitiveType()
   * @generated
   */
  int PRIMITIVE_TYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE__NAME = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Primitive Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_TYPE_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.impl.ComplexTypeRefImpl <em>Complex Type Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.impl.ComplexTypeRefImpl
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getComplexTypeRef()
   * @generated
   */
  int COMPLEX_TYPE_REF = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TYPE_REF__TYPE = TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Complex Type Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_TYPE_REF_FEATURE_COUNT = TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.impl.ElementImpl
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.impl.EntityImpl
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__FIELDS = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.impl.EntityFieldImpl <em>Entity Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.impl.EntityFieldImpl
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getEntityField()
   * @generated
   */
  int ENTITY_FIELD = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FIELD__TYPE = 1;

  /**
   * The feature id for the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FIELD__LIST = 2;

  /**
   * The feature id for the '<em><b>Nullable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FIELD__NULLABLE = 3;

  /**
   * The feature id for the '<em><b>Relation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FIELD__RELATION = 4;

  /**
   * The number of structural features of the '<em>Entity Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FIELD_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.impl.EnumDslImpl <em>Enum Dsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.impl.EnumDslImpl
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getEnumDsl()
   * @generated
   */
  int ENUM_DSL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_DSL__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Literals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_DSL__LITERALS = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Enum Dsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_DSL_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.impl.EnumLiteralImpl <em>Enum Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.impl.EnumLiteralImpl
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getEnumLiteral()
   * @generated
   */
  int ENUM_LITERAL = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_LITERAL__NAME = 0;

  /**
   * The number of structural features of the '<em>Enum Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_LITERAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.com.lucra.lucraDSL.RelationType <em>Relation Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.com.lucra.lucraDSL.RelationType
   * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getRelationType()
   * @generated
   */
  int RELATION_TYPE = 9;


  /**
   * Returns the meta object for class '{@link br.com.lucra.lucraDSL.LucraDSL <em>Lucra DSL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lucra DSL</em>'.
   * @see br.com.lucra.lucraDSL.LucraDSL
   * @generated
   */
  EClass getLucraDSL();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.lucra.lucraDSL.LucraDSL#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see br.com.lucra.lucraDSL.LucraDSL#getElements()
   * @see #getLucraDSL()
   * @generated
   */
  EReference getLucraDSL_Elements();

  /**
   * Returns the meta object for class '{@link br.com.lucra.lucraDSL.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see br.com.lucra.lucraDSL.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link br.com.lucra.lucraDSL.PrimitiveType <em>Primitive Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Primitive Type</em>'.
   * @see br.com.lucra.lucraDSL.PrimitiveType
   * @generated
   */
  EClass getPrimitiveType();

  /**
   * Returns the meta object for the attribute '{@link br.com.lucra.lucraDSL.PrimitiveType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.com.lucra.lucraDSL.PrimitiveType#getName()
   * @see #getPrimitiveType()
   * @generated
   */
  EAttribute getPrimitiveType_Name();

  /**
   * Returns the meta object for class '{@link br.com.lucra.lucraDSL.ComplexTypeRef <em>Complex Type Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Type Ref</em>'.
   * @see br.com.lucra.lucraDSL.ComplexTypeRef
   * @generated
   */
  EClass getComplexTypeRef();

  /**
   * Returns the meta object for the reference '{@link br.com.lucra.lucraDSL.ComplexTypeRef#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see br.com.lucra.lucraDSL.ComplexTypeRef#getType()
   * @see #getComplexTypeRef()
   * @generated
   */
  EReference getComplexTypeRef_Type();

  /**
   * Returns the meta object for class '{@link br.com.lucra.lucraDSL.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see br.com.lucra.lucraDSL.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link br.com.lucra.lucraDSL.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.com.lucra.lucraDSL.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for class '{@link br.com.lucra.lucraDSL.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see br.com.lucra.lucraDSL.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.lucra.lucraDSL.Entity#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see br.com.lucra.lucraDSL.Entity#getFields()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Fields();

  /**
   * Returns the meta object for class '{@link br.com.lucra.lucraDSL.EntityField <em>Entity Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity Field</em>'.
   * @see br.com.lucra.lucraDSL.EntityField
   * @generated
   */
  EClass getEntityField();

  /**
   * Returns the meta object for the attribute '{@link br.com.lucra.lucraDSL.EntityField#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.com.lucra.lucraDSL.EntityField#getName()
   * @see #getEntityField()
   * @generated
   */
  EAttribute getEntityField_Name();

  /**
   * Returns the meta object for the containment reference '{@link br.com.lucra.lucraDSL.EntityField#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see br.com.lucra.lucraDSL.EntityField#getType()
   * @see #getEntityField()
   * @generated
   */
  EReference getEntityField_Type();

  /**
   * Returns the meta object for the attribute '{@link br.com.lucra.lucraDSL.EntityField#isList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>List</em>'.
   * @see br.com.lucra.lucraDSL.EntityField#isList()
   * @see #getEntityField()
   * @generated
   */
  EAttribute getEntityField_List();

  /**
   * Returns the meta object for the attribute '{@link br.com.lucra.lucraDSL.EntityField#isNullable <em>Nullable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nullable</em>'.
   * @see br.com.lucra.lucraDSL.EntityField#isNullable()
   * @see #getEntityField()
   * @generated
   */
  EAttribute getEntityField_Nullable();

  /**
   * Returns the meta object for the attribute '{@link br.com.lucra.lucraDSL.EntityField#getRelation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Relation</em>'.
   * @see br.com.lucra.lucraDSL.EntityField#getRelation()
   * @see #getEntityField()
   * @generated
   */
  EAttribute getEntityField_Relation();

  /**
   * Returns the meta object for class '{@link br.com.lucra.lucraDSL.EnumDsl <em>Enum Dsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Dsl</em>'.
   * @see br.com.lucra.lucraDSL.EnumDsl
   * @generated
   */
  EClass getEnumDsl();

  /**
   * Returns the meta object for the containment reference list '{@link br.com.lucra.lucraDSL.EnumDsl#getLiterals <em>Literals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Literals</em>'.
   * @see br.com.lucra.lucraDSL.EnumDsl#getLiterals()
   * @see #getEnumDsl()
   * @generated
   */
  EReference getEnumDsl_Literals();

  /**
   * Returns the meta object for class '{@link br.com.lucra.lucraDSL.EnumLiteral <em>Enum Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Literal</em>'.
   * @see br.com.lucra.lucraDSL.EnumLiteral
   * @generated
   */
  EClass getEnumLiteral();

  /**
   * Returns the meta object for the attribute '{@link br.com.lucra.lucraDSL.EnumLiteral#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.com.lucra.lucraDSL.EnumLiteral#getName()
   * @see #getEnumLiteral()
   * @generated
   */
  EAttribute getEnumLiteral_Name();

  /**
   * Returns the meta object for enum '{@link br.com.lucra.lucraDSL.RelationType <em>Relation Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Relation Type</em>'.
   * @see br.com.lucra.lucraDSL.RelationType
   * @generated
   */
  EEnum getRelationType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LucraDSLFactory getLucraDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.impl.LucraDSLImpl <em>Lucra DSL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.impl.LucraDSLImpl
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getLucraDSL()
     * @generated
     */
    EClass LUCRA_DSL = eINSTANCE.getLucraDSL();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LUCRA_DSL__ELEMENTS = eINSTANCE.getLucraDSL_Elements();

    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.impl.TypeImpl
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.impl.PrimitiveTypeImpl <em>Primitive Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.impl.PrimitiveTypeImpl
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getPrimitiveType()
     * @generated
     */
    EClass PRIMITIVE_TYPE = eINSTANCE.getPrimitiveType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIMITIVE_TYPE__NAME = eINSTANCE.getPrimitiveType_Name();

    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.impl.ComplexTypeRefImpl <em>Complex Type Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.impl.ComplexTypeRefImpl
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getComplexTypeRef()
     * @generated
     */
    EClass COMPLEX_TYPE_REF = eINSTANCE.getComplexTypeRef();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_TYPE_REF__TYPE = eINSTANCE.getComplexTypeRef_Type();

    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.impl.ElementImpl
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.impl.EntityImpl
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__FIELDS = eINSTANCE.getEntity_Fields();

    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.impl.EntityFieldImpl <em>Entity Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.impl.EntityFieldImpl
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getEntityField()
     * @generated
     */
    EClass ENTITY_FIELD = eINSTANCE.getEntityField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_FIELD__NAME = eINSTANCE.getEntityField_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY_FIELD__TYPE = eINSTANCE.getEntityField_Type();

    /**
     * The meta object literal for the '<em><b>List</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_FIELD__LIST = eINSTANCE.getEntityField_List();

    /**
     * The meta object literal for the '<em><b>Nullable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_FIELD__NULLABLE = eINSTANCE.getEntityField_Nullable();

    /**
     * The meta object literal for the '<em><b>Relation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_FIELD__RELATION = eINSTANCE.getEntityField_Relation();

    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.impl.EnumDslImpl <em>Enum Dsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.impl.EnumDslImpl
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getEnumDsl()
     * @generated
     */
    EClass ENUM_DSL = eINSTANCE.getEnumDsl();

    /**
     * The meta object literal for the '<em><b>Literals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_DSL__LITERALS = eINSTANCE.getEnumDsl_Literals();

    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.impl.EnumLiteralImpl <em>Enum Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.impl.EnumLiteralImpl
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getEnumLiteral()
     * @generated
     */
    EClass ENUM_LITERAL = eINSTANCE.getEnumLiteral();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_LITERAL__NAME = eINSTANCE.getEnumLiteral_Name();

    /**
     * The meta object literal for the '{@link br.com.lucra.lucraDSL.RelationType <em>Relation Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.com.lucra.lucraDSL.RelationType
     * @see br.com.lucra.lucraDSL.impl.LucraDSLPackageImpl#getRelationType()
     * @generated
     */
    EEnum RELATION_TYPE = eINSTANCE.getRelationType();

  }

} //LucraDSLPackage
