/**
 * generated by Xtext 2.41.0
 */
package br.com.lucra.lucraDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primitive Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.com.lucra.lucraDSL.PrimitiveType#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see br.com.lucra.lucraDSL.LucraDSLPackage#getPrimitiveType()
 * @model
 * @generated
 */
public interface PrimitiveType extends Type
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.com.lucra.lucraDSL.LucraDSLPackage#getPrimitiveType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.com.lucra.lucraDSL.PrimitiveType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // PrimitiveType
