/**
 * generated by Xtext 2.41.0
 */
package br.com.lucra.lucraDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.com.lucra.lucraDSL.LucraDSLPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
