/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.ui;

import com.google.inject.Injector;
import lucradsl.ui.internal.LucradslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LucraDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LucradslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LucradslActivator activator = LucradslActivator.getInstance();
		return activator != null ? activator.getInjector(LucradslActivator.BR_COM_LUCRA_LUCRADSL) : null;
	}

}
