/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLucraDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(br.com.lucra.lucraDSL.LucraDSLPackage.eINSTANCE);
		return result;
	}
}
