/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.ui.tests;

import com.google.inject.Injector;
import lucradsl.ui.internal.LucradslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LucraDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LucradslActivator.getInstance().getInjector("br.com.lucra.LucraDSL");
	}

}
