/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LucraDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("br/com/lucra/parser/antlr/internal/InternalLucraDSL.tokens");
	}
}
