/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.parser.antlr;

import br.com.lucra.parser.antlr.internal.InternalLucraDSLParser;
import br.com.lucra.services.LucraDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LucraDSLParser extends AbstractAntlrParser {

	@Inject
	private LucraDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLucraDSLParser createParser(XtextTokenStream stream) {
		return new InternalLucraDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LucraDSL";
	}

	public LucraDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LucraDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
