/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.serializer;

import br.com.lucra.lucraDSL.ComplexTypeRef;
import br.com.lucra.lucraDSL.Entity;
import br.com.lucra.lucraDSL.EntityField;
import br.com.lucra.lucraDSL.EnumDsl;
import br.com.lucra.lucraDSL.EnumLiteral;
import br.com.lucra.lucraDSL.LucraDSL;
import br.com.lucra.lucraDSL.LucraDSLPackage;
import br.com.lucra.lucraDSL.PrimitiveType;
import br.com.lucra.services.LucraDSLGrammarAccess;
import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class LucraDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private LucraDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == LucraDSLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case LucraDSLPackage.COMPLEX_TYPE_REF:
				sequence_ComplexTypeRef(context, (ComplexTypeRef) semanticObject); 
				return; 
			case LucraDSLPackage.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case LucraDSLPackage.ENTITY_FIELD:
				sequence_EntityField(context, (EntityField) semanticObject); 
				return; 
			case LucraDSLPackage.ENUM_DSL:
				sequence_EnumDsl(context, (EnumDsl) semanticObject); 
				return; 
			case LucraDSLPackage.ENUM_LITERAL:
				sequence_EnumLiteral(context, (EnumLiteral) semanticObject); 
				return; 
			case LucraDSLPackage.LUCRA_DSL:
				sequence_LucraDSL(context, (LucraDSL) semanticObject); 
				return; 
			case LucraDSLPackage.PRIMITIVE_TYPE:
				sequence_PrimitiveType(context, (PrimitiveType) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Type returns ComplexTypeRef
	 *     ComplexTypeRef returns ComplexTypeRef
	 *
	 * Constraint:
	 *     type=[Element|ID]
	 * </pre>
	 */
	protected void sequence_ComplexTypeRef(ISerializationContext context, ComplexTypeRef semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LucraDSLPackage.Literals.COMPLEX_TYPE_REF__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LucraDSLPackage.Literals.COMPLEX_TYPE_REF__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getComplexTypeRefAccess().getTypeElementIDTerminalRuleCall_0_1(), semanticObject.eGet(LucraDSLPackage.Literals.COMPLEX_TYPE_REF__TYPE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EntityField returns EntityField
	 *
	 * Constraint:
	 *     (name=ID type=Type list?='*'? nullable?='?'? relation=RelationType?)
	 * </pre>
	 */
	protected void sequence_EntityField(ISerializationContext context, EntityField semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Element returns Entity
	 *     Entity returns Entity
	 *
	 * Constraint:
	 *     (name=ID fields+=EntityField*)
	 * </pre>
	 */
	protected void sequence_Entity(ISerializationContext context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Element returns EnumDsl
	 *     EnumDsl returns EnumDsl
	 *
	 * Constraint:
	 *     (name=ID literals+=EnumLiteral*)
	 * </pre>
	 */
	protected void sequence_EnumDsl(ISerializationContext context, EnumDsl semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EnumLiteral returns EnumLiteral
	 *
	 * Constraint:
	 *     name=ID
	 * </pre>
	 */
	protected void sequence_EnumLiteral(ISerializationContext context, EnumLiteral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, LucraDSLPackage.Literals.ENUM_LITERAL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, LucraDSLPackage.Literals.ENUM_LITERAL__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnumLiteralAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LucraDSL returns LucraDSL
	 *
	 * Constraint:
	 *     elements+=Element+
	 * </pre>
	 */
	protected void sequence_LucraDSL(ISerializationContext context, LucraDSL semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Type returns PrimitiveType
	 *     PrimitiveType returns PrimitiveType
	 *
	 * Constraint:
	 *     (
	 *         name='string' | 
	 *         name='number' | 
	 *         name='date' | 
	 *         name='uuid' | 
	 *         name='money' | 
	 *         name='boolean'
	 *     )
	 * </pre>
	 */
	protected void sequence_PrimitiveType(ISerializationContext context, PrimitiveType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
