/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class LucraDSLScopeProvider extends AbstractLucraDSLScopeProvider {

}
