/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.ide.contentassist.antlr;

import br.com.lucra.ide.contentassist.antlr.internal.InternalLucraDSLParser;
import br.com.lucra.services.LucraDSLGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class LucraDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(LucraDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, LucraDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getPrimitiveTypeAccess().getNameAlternatives_1_0(), "rule__PrimitiveType__NameAlternatives_1_0");
			builder.put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
			builder.put(grammarAccess.getRelationTypeAccess().getAlternatives(), "rule__RelationType__Alternatives");
			builder.put(grammarAccess.getPrimitiveTypeAccess().getGroup(), "rule__PrimitiveType__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getEntityFieldAccess().getGroup(), "rule__EntityField__Group__0");
			builder.put(grammarAccess.getEnumDslAccess().getGroup(), "rule__EnumDsl__Group__0");
			builder.put(grammarAccess.getLucraDSLAccess().getElementsAssignment(), "rule__LucraDSL__ElementsAssignment");
			builder.put(grammarAccess.getPrimitiveTypeAccess().getNameAssignment_1(), "rule__PrimitiveType__NameAssignment_1");
			builder.put(grammarAccess.getComplexTypeRefAccess().getTypeAssignment(), "rule__ComplexTypeRef__TypeAssignment");
			builder.put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
			builder.put(grammarAccess.getEntityAccess().getFieldsAssignment_3(), "rule__Entity__FieldsAssignment_3");
			builder.put(grammarAccess.getEntityFieldAccess().getNameAssignment_0(), "rule__EntityField__NameAssignment_0");
			builder.put(grammarAccess.getEntityFieldAccess().getTypeAssignment_1(), "rule__EntityField__TypeAssignment_1");
			builder.put(grammarAccess.getEntityFieldAccess().getListAssignment_2(), "rule__EntityField__ListAssignment_2");
			builder.put(grammarAccess.getEntityFieldAccess().getNullableAssignment_3(), "rule__EntityField__NullableAssignment_3");
			builder.put(grammarAccess.getEntityFieldAccess().getRelationAssignment_4(), "rule__EntityField__RelationAssignment_4");
			builder.put(grammarAccess.getEnumDslAccess().getNameAssignment_1(), "rule__EnumDsl__NameAssignment_1");
			builder.put(grammarAccess.getEnumDslAccess().getLiteralsAssignment_3(), "rule__EnumDsl__LiteralsAssignment_3");
			builder.put(grammarAccess.getEnumLiteralAccess().getNameAssignment(), "rule__EnumLiteral__NameAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private LucraDSLGrammarAccess grammarAccess;

	@Override
	protected InternalLucraDSLParser createParser() {
		InternalLucraDSLParser result = new InternalLucraDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public LucraDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LucraDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
