/**
 * generated by Xtext 2.41.0
 */
package br.com.lucra.generator;

import br.com.lucra.generator.utils.ClassUtils;
import br.com.lucra.lucraDSL.Element;
import br.com.lucra.utils.ImportManager;
import com.google.common.collect.Iterables;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

@SuppressWarnings("all")
public class LucraDSLGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    Iterable<Element> _filter = Iterables.<Element>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), Element.class);
    for (final Element element : _filter) {
      {
        System.out.println(String.format("1 Generating %s", element.getName()));
        fsa.generateFile(
          ClassUtils.generateFilePath(element).toString(), 
          this.compile(element));
      }
    }
  }

  private CharSequence compile(final Element element) {
    CharSequence _xblockexpression = null;
    {
      final ImportManager importManager = new ImportManager();
      final CharSequence classPackage = ClassUtils.generatePackagePath(element);
      final CharSequence classType = ClassUtils.getClassType(element);
      final CharSequence className = ClassUtils.generateClassName(element);
      final CharSequence classAnnotations = ClassUtils.generateClassAnnotations(element, importManager);
      final CharSequence classFields = ClassUtils.generateClassFields(element, importManager);
      final CharSequence classImports = ClassUtils.generateClassImports(element, importManager);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("package ");
      _builder.append(classPackage);
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.newLine();
      _builder.append(classImports);
      _builder.newLineIfNotEmpty();
      _builder.newLine();
      _builder.append(classAnnotations);
      _builder.newLineIfNotEmpty();
      _builder.append("public ");
      _builder.append(classType);
      _builder.append(" ");
      _builder.append(className);
      _builder.append(" {");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append(classFields, "\t");
      _builder.newLineIfNotEmpty();
      _builder.append("}");
      _builder.newLine();
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }
}
