/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LucraDSLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class LucraDSLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.LucraDSL");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsElementParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//LucraDSL:
		//    (elements+=Element)*;
		@Override public ParserRule getRule() { return rule; }
		
		//(elements+=Element)*
		public Assignment getElementsAssignment() { return cElementsAssignment; }
		
		//Element
		public RuleCall getElementsElementParserRuleCall_0() { return cElementsElementParserRuleCall_0; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPrimitiveTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComplexTypeRefParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Type:
		//    PrimitiveType | ComplexTypeRef;
		@Override public ParserRule getRule() { return rule; }
		
		//PrimitiveType | ComplexTypeRef
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PrimitiveType
		public RuleCall getPrimitiveTypeParserRuleCall_0() { return cPrimitiveTypeParserRuleCall_0; }
		
		//ComplexTypeRef
		public RuleCall getComplexTypeRefParserRuleCall_1() { return cComplexTypeRefParserRuleCall_1; }
	}
	public class PrimitiveTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.PrimitiveType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPrimitiveTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cNameAlternatives_1_0 = (Alternatives)cNameAssignment_1.eContents().get(0);
		private final Keyword cNameStringKeyword_1_0_0 = (Keyword)cNameAlternatives_1_0.eContents().get(0);
		private final Keyword cNameNumberKeyword_1_0_1 = (Keyword)cNameAlternatives_1_0.eContents().get(1);
		private final Keyword cNameDateKeyword_1_0_2 = (Keyword)cNameAlternatives_1_0.eContents().get(2);
		private final Keyword cNameUuidKeyword_1_0_3 = (Keyword)cNameAlternatives_1_0.eContents().get(3);
		private final Keyword cNameMoneyKeyword_1_0_4 = (Keyword)cNameAlternatives_1_0.eContents().get(4);
		private final Keyword cNameBooleanKeyword_1_0_5 = (Keyword)cNameAlternatives_1_0.eContents().get(5);
		
		//PrimitiveType:
		//    {PrimitiveType} name=('string' | 'number' | 'date' | 'uuid' | 'money' | 'boolean');
		@Override public ParserRule getRule() { return rule; }
		
		//{PrimitiveType} name=('string' | 'number' | 'date' | 'uuid' | 'money' | 'boolean')
		public Group getGroup() { return cGroup; }
		
		//{PrimitiveType}
		public Action getPrimitiveTypeAction_0() { return cPrimitiveTypeAction_0; }
		
		//name=('string' | 'number' | 'date' | 'uuid' | 'money' | 'boolean')
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//('string' | 'number' | 'date' | 'uuid' | 'money' | 'boolean')
		public Alternatives getNameAlternatives_1_0() { return cNameAlternatives_1_0; }
		
		//'string'
		public Keyword getNameStringKeyword_1_0_0() { return cNameStringKeyword_1_0_0; }
		
		//'number'
		public Keyword getNameNumberKeyword_1_0_1() { return cNameNumberKeyword_1_0_1; }
		
		//'date'
		public Keyword getNameDateKeyword_1_0_2() { return cNameDateKeyword_1_0_2; }
		
		//'uuid'
		public Keyword getNameUuidKeyword_1_0_3() { return cNameUuidKeyword_1_0_3; }
		
		//'money'
		public Keyword getNameMoneyKeyword_1_0_4() { return cNameMoneyKeyword_1_0_4; }
		
		//'boolean'
		public Keyword getNameBooleanKeyword_1_0_5() { return cNameBooleanKeyword_1_0_5; }
	}
	public class ComplexTypeRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.ComplexTypeRef");
		private final Assignment cTypeAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cTypeElementCrossReference_0 = (CrossReference)cTypeAssignment.eContents().get(0);
		private final RuleCall cTypeElementIDTerminalRuleCall_0_1 = (RuleCall)cTypeElementCrossReference_0.eContents().get(1);
		
		//ComplexTypeRef:
		//    type=[Element];
		@Override public ParserRule getRule() { return rule; }
		
		//type=[Element]
		public Assignment getTypeAssignment() { return cTypeAssignment; }
		
		//[Element]
		public CrossReference getTypeElementCrossReference_0() { return cTypeElementCrossReference_0; }
		
		//ID
		public RuleCall getTypeElementIDTerminalRuleCall_0_1() { return cTypeElementIDTerminalRuleCall_0_1; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEntityParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEnumDslParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Element:
		//    Entity | EnumDsl;
		@Override public ParserRule getRule() { return rule; }
		
		//Entity | EnumDsl
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Entity
		public RuleCall getEntityParserRuleCall_0() { return cEntityParserRuleCall_0; }
		
		//EnumDsl
		public RuleCall getEnumDslParserRuleCall_1() { return cEnumDslParserRuleCall_1; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFieldsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFieldsEntityFieldParserRuleCall_3_0 = (RuleCall)cFieldsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//// <entity>
		//Entity:
		//    'entity' name=ID '{'
		//        (fields+=EntityField)*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'entity' name=ID '{'
		//    (fields+=EntityField)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'entity'
		public Keyword getEntityKeyword_0() { return cEntityKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(fields+=EntityField)*
		public Assignment getFieldsAssignment_3() { return cFieldsAssignment_3; }
		
		//EntityField
		public RuleCall getFieldsEntityFieldParserRuleCall_3_0() { return cFieldsEntityFieldParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EntityFieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.EntityField");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cListAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cListAsteriskKeyword_2_0 = (Keyword)cListAssignment_2.eContents().get(0);
		private final Assignment cNullableAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cNullableQuestionMarkKeyword_3_0 = (Keyword)cNullableAssignment_3.eContents().get(0);
		private final Assignment cRelationAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRelationRelationTypeEnumRuleCall_4_0 = (RuleCall)cRelationAssignment_4.eContents().get(0);
		
		//EntityField:
		//    name=ID type=Type (list?='*')? (nullable?='?')? (relation=RelationType)?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID type=Type (list?='*')? (nullable?='?')? (relation=RelationType)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//type=Type
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_1_0() { return cTypeTypeParserRuleCall_1_0; }
		
		//(list?='*')?
		public Assignment getListAssignment_2() { return cListAssignment_2; }
		
		//'*'
		public Keyword getListAsteriskKeyword_2_0() { return cListAsteriskKeyword_2_0; }
		
		//(nullable?='?')?
		public Assignment getNullableAssignment_3() { return cNullableAssignment_3; }
		
		//'?'
		public Keyword getNullableQuestionMarkKeyword_3_0() { return cNullableQuestionMarkKeyword_3_0; }
		
		//(relation=RelationType)?
		public Assignment getRelationAssignment_4() { return cRelationAssignment_4; }
		
		//RelationType
		public RuleCall getRelationRelationTypeEnumRuleCall_4_0() { return cRelationRelationTypeEnumRuleCall_4_0; }
	}
	public class EnumDslElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.EnumDsl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEnumKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLiteralsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLiteralsEnumLiteralParserRuleCall_3_0 = (RuleCall)cLiteralsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//            // As entidades se conhecem, mas têm ciclos de vida independentes.
		//// </entity>
		//// <enum>
		//EnumDsl:
		//    'enum' name=ID '{'
		//        (literals+=EnumLiteral)*
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'enum' name=ID '{'
		//    (literals+=EnumLiteral)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'enum'
		public Keyword getEnumKeyword_0() { return cEnumKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(literals+=EnumLiteral)*
		public Assignment getLiteralsAssignment_3() { return cLiteralsAssignment_3; }
		
		//EnumLiteral
		public RuleCall getLiteralsEnumLiteralParserRuleCall_3_0() { return cLiteralsEnumLiteralParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EnumLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.EnumLiteral");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//EnumLiteral:
		//    name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	
	public class RelationTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "br.com.lucra.LucraDSL.RelationType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCONTAINSEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCONTAINSContainsKeyword_0_0 = (Keyword)cCONTAINSEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCONTAINEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCONTAINEDContainedKeyword_1_0 = (Keyword)cCONTAINEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cREFERSEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cREFERSRefersKeyword_2_0 = (Keyword)cREFERSEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum RelationType:
		//    CONTAINS = 'contains' |     // A Entidade controla o ciclo de vida da outra
		//    CONTAINED = 'contained' |     // A entidade atual pertence à entidade alvo. Ela não vive sem o dono.
		//    REFERS = 'refers';
		public EnumRule getRule() { return rule; }
		
		//CONTAINS = 'contains' |     // A Entidade controla o ciclo de vida da outra
		//CONTAINED = 'contained' |     // A entidade atual pertence à entidade alvo. Ela não vive sem o dono.
		//REFERS = 'refers'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CONTAINS = 'contains'
		public EnumLiteralDeclaration getCONTAINSEnumLiteralDeclaration_0() { return cCONTAINSEnumLiteralDeclaration_0; }
		
		//'contains'
		public Keyword getCONTAINSContainsKeyword_0_0() { return cCONTAINSContainsKeyword_0_0; }
		
		// // A Entidade controla o ciclo de vida da outra
		//CONTAINED = 'contained'
		public EnumLiteralDeclaration getCONTAINEDEnumLiteralDeclaration_1() { return cCONTAINEDEnumLiteralDeclaration_1; }
		
		//'contained'
		public Keyword getCONTAINEDContainedKeyword_1_0() { return cCONTAINEDContainedKeyword_1_0; }
		
		// // A entidade atual pertence à entidade alvo. Ela não vive sem o dono.
		//REFERS = 'refers'
		public EnumLiteralDeclaration getREFERSEnumLiteralDeclaration_2() { return cREFERSEnumLiteralDeclaration_2; }
		
		//'refers'
		public Keyword getREFERSRefersKeyword_2_0() { return cREFERSRefersKeyword_2_0; }
	}
	
	private final LucraDSLElements pLucraDSL;
	private final TypeElements pType;
	private final PrimitiveTypeElements pPrimitiveType;
	private final ComplexTypeRefElements pComplexTypeRef;
	private final ElementElements pElement;
	private final EntityElements pEntity;
	private final EntityFieldElements pEntityField;
	private final RelationTypeElements eRelationType;
	private final EnumDslElements pEnumDsl;
	private final EnumLiteralElements pEnumLiteral;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LucraDSLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pLucraDSL = new LucraDSLElements();
		this.pType = new TypeElements();
		this.pPrimitiveType = new PrimitiveTypeElements();
		this.pComplexTypeRef = new ComplexTypeRefElements();
		this.pElement = new ElementElements();
		this.pEntity = new EntityElements();
		this.pEntityField = new EntityFieldElements();
		this.eRelationType = new RelationTypeElements();
		this.pEnumDsl = new EnumDslElements();
		this.pEnumLiteral = new EnumLiteralElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("br.com.lucra.LucraDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//LucraDSL:
	//    (elements+=Element)*;
	public LucraDSLElements getLucraDSLAccess() {
		return pLucraDSL;
	}
	
	public ParserRule getLucraDSLRule() {
		return getLucraDSLAccess().getRule();
	}
	
	//Type:
	//    PrimitiveType | ComplexTypeRef;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//PrimitiveType:
	//    {PrimitiveType} name=('string' | 'number' | 'date' | 'uuid' | 'money' | 'boolean');
	public PrimitiveTypeElements getPrimitiveTypeAccess() {
		return pPrimitiveType;
	}
	
	public ParserRule getPrimitiveTypeRule() {
		return getPrimitiveTypeAccess().getRule();
	}
	
	//ComplexTypeRef:
	//    type=[Element];
	public ComplexTypeRefElements getComplexTypeRefAccess() {
		return pComplexTypeRef;
	}
	
	public ParserRule getComplexTypeRefRule() {
		return getComplexTypeRefAccess().getRule();
	}
	
	//Element:
	//    Entity | EnumDsl;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//// <entity>
	//Entity:
	//    'entity' name=ID '{'
	//        (fields+=EntityField)*
	//    '}';
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//EntityField:
	//    name=ID type=Type (list?='*')? (nullable?='?')? (relation=RelationType)?;
	public EntityFieldElements getEntityFieldAccess() {
		return pEntityField;
	}
	
	public ParserRule getEntityFieldRule() {
		return getEntityFieldAccess().getRule();
	}
	
	//enum RelationType:
	//    CONTAINS = 'contains' |     // A Entidade controla o ciclo de vida da outra
	//    CONTAINED = 'contained' |     // A entidade atual pertence à entidade alvo. Ela não vive sem o dono.
	//    REFERS = 'refers';
	public RelationTypeElements getRelationTypeAccess() {
		return eRelationType;
	}
	
	public EnumRule getRelationTypeRule() {
		return getRelationTypeAccess().getRule();
	}
	
	//            // As entidades se conhecem, mas têm ciclos de vida independentes.
	//// </entity>
	//// <enum>
	//EnumDsl:
	//    'enum' name=ID '{'
	//        (literals+=EnumLiteral)*
	//    '}';
	public EnumDslElements getEnumDslAccess() {
		return pEnumDsl;
	}
	
	public ParserRule getEnumDslRule() {
		return getEnumDslAccess().getRule();
	}
	
	//EnumLiteral:
	//    name=ID;
	public EnumLiteralElements getEnumLiteralAccess() {
		return pEnumLiteral;
	}
	
	public ParserRule getEnumLiteralRule() {
		return getEnumLiteralAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
