/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.ide;

import br.com.lucra.LucraDSLRuntimeModule;
import br.com.lucra.LucraDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LucraDSLIdeSetup extends LucraDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LucraDSLRuntimeModule(), new LucraDSLIdeModule()));
	}
	
}
