/*
 * generated by Xtext 2.41.0
 */
package br.com.lucra.validation;

import org.eclipse.xtext.validation.Check;
import br.com.lucra.lucraDSL.EntityField;
import br.com.lucra.lucraDSL.LucraDSLPackage;
import br.com.lucra.lucraDSL.PrimitiveType;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class LucraDSLValidator extends AbstractLucraDSLValidator {

	@Check
	public void checkUuidFieldModifiers(EntityField field) {
		validateIdNotNullableOrList(field);
	}
	
	private void validateIdNotNullableOrList(EntityField field) {
		if (!(field.getType() instanceof PrimitiveType)) {
			return;
		}

		PrimitiveType type = (PrimitiveType) field.getType();
		
		if (!"id".equals(type.getName())) {
			return;
		}

		if (field.isList()) {
			error(
				"O tipo 'id' não pode ser uma lista (*)",
				LucraDSLPackage.Literals.ENTITY_FIELD__LIST,
				"idCannotBeList"
			);
		}

		if (field.isNullable()) {
			error(
				"O tipo 'id' não pode ser nullable (?)",
				LucraDSLPackage.Literals.ENTITY_FIELD__NULLABLE,
				"idCannotBeNullable"
			);
		}
	}
}