name: Snapshot

on:
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Generate snapshot version
        working-directory: lucradsl.parent
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          TIMESTAMP=$(date +%s%3N)

          SNAPSHOT="$VERSION-$TIMESTAMP-SNAPSHOT"

          mvn versions:set -DnewVersion=$SNAPSHOT -DgenerateBackupPoms=false

      - name: Deploy snapshot
        working-directory: lucradsl.parent
        run: mvn -B install -pl lucradsl.target -DskipTests && mvn -B clean deploy -pl lucradsl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
